version: "3"
services:
  node:
    build: .
    volumes:
      - ./:/app
      - content_data:/data/content
    ports:
      - "8080:8080"
    links:
      - mongo
    command: ["yarn", "run", "start"]
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
        #  nginx: make custom image that serves the client

volumes:
  mongo_data:
  content_data:
